/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-surface-variant": "#475569",
              "on-primary-fixed": "#172554",
              "on-secondary-fixed-variant": "#334155",
              "secondary-fixed-dim": "#cbd5e1",
              "on-error-container": "#991b1b",
              "surface-container": "#f1f5f9",
              "surface-container-lowest": "#ffffff",
              "on-primary": "#ffffff",
              "on-primary-fixed-variant": "#1e40af",
              "primary-fixed-dim": "#93c5fd",
              "background": "#f8fafc",
              "surface-tint": "#2563eb",
              "on-tertiary-fixed-variant": "#334155",
              "on-error": "#ffffff",
              "inverse-on-surface": "#f1f5f9",
              "primary-container": "#1d4ed8",
              "secondary-fixed": "#e2e8f0",
              "error": "#dc2626",
              "on-primary-container": "#bfdbfe",
              "on-background": "#0f172a",
              "primary-fixed": "#dbeafe",
              "tertiary": "#475569",
              "on-secondary-fixed": "#1e293b",
              "outline-variant": "#cbd5e1",
              "primary": "#2563eb",
              "outline": "#94a3b8",
              "surface-variant": "#e2e8f0",
              "on-tertiary-fixed": "#0f172a",
              "error-container": "#fee2e2",
              "on-secondary-container": "#334155",
              "surface-container-low": "#f8fafc",
              "secondary": "#64748b",
              "inverse-surface": "#1e293b",
              "secondary-container": "#e2e8f0",
              "surface-dim": "#e2e8f0",
              "tertiary-fixed": "#e2e8f0",
              "surface-container-high": "#e2e8f0",
              "surface": "#ffffff",
              "on-tertiary": "#ffffff",
              "tertiary-fixed-dim": "#cbd5e1",
              "on-secondary": "#ffffff",
              "surface-container-highest": "#e2e8f0",
              "on-tertiary-container": "#cbd5e1",
              "surface-bright": "#ffffff",
              "on-surface": "#0f172a",
              "tertiary-container": "#334155",
              "inverse-primary": "#93c5fd"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Plus Jakarta Sans"],
              "body": ["Plus Jakarta Sans"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
